n1 = int(input())
n2 = int(input())
n3 = int(input())
n4 = int(input())
n5 = int(input())
n6 = int(input())
n7 = int(input())
numbers = [n1,n2,n3,n4,n5,n6,n7]
mayor = max(numbers)
menor = min(numbers)
promedio = (sum(numbers)//7)
print(mayor)
print(menor)
print(promedio)